server {
  listen 80;

  location = /health {
    default_type application/json;
    return 200 '{"service":"gateway","status":"UP"}';
  }

  location /entities {
    proxy_pass http://entity-service:3001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /inventory {
    proxy_pass http://inventory-service:3002;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /permits {
    proxy_pass http://permit-service:3003;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
